version: 2
registries:
  approvalmax-github:
    type: nuget-feed
    url: https://nuget.pkg.github.com
    # The token requires the `read:packages` scope only
    token: ${{ secrets.DEPENDABOT_GITHUB_PACKAGES_TOKEN }}

updates:
  - package-ecosystem: 'nuget'
    directory: '/IPPDotNetDevKitCSV3/Code'
    reviewers:
      - 'ApprovalMax/ap-be'
    registries:
      - approvalmax-github
    schedule:
      interval: 'weekly'
    groups:
      all-nugets:
        patterns:
          - '*'
    ignore:
      - dependency-name: 'JetBrains.ReSharper.GlobalTools'
